import Head from "next/head";
import Layout from "@/components/organisms/Layout";
import { useCallback, useEffect, useState } from "react";
import Button from "@/components/atoms/Button";
import { odtService } from "@/services/odt-service";
import { odtType } from "@/services/data-types/odt-type";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [odts, setodts] = useState<odtType[]>([]);

  const getodts = useCallback(async () => {
    setIsLoading(true);

    try {
      const response = await odtService();

      if (response.error) {
        alert(response.message);
      } else {
        setodts(response.data);
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    getodts();
  }, [getodts]);

  return (
    <>
      <Head>
        <title>Data Obat dan Tindakan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container-fluid px-4">
          <h1 className="mt-4">Data Obat dan Tindakan</h1>
          <ol className="breadcrumb mb-4">
            <li className="breadcrumb-item active">Obat dan Tindakan</li>
          </ol>
          <div className="card mb-4">
            <div className="card-header">
              <i className="fas fa-table me-1"></i>
              Tabel Obat dan Tindakan{" "}
              <div className="d-flex justify-content-end gap-1">
                <Button
                  type="button"
                  onClickButton={getodts}
                  isLoading={isLoading}
                  className={["btn btn-primary btn-sm"]}
                >
                  <i className="fas fa-sync-alt me-1"></i>
                </Button>
                <Button
                  type="link"
                  href="/odt/create"
                  className={["btn btn-primary btn-sm me-2"]}
                >
                  Tambah Data
                </Button>
              </div>
            </div>
            <div className="card-body">
              <table className="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nama Obat / Tindakan</th>
                    <th scope="col">Tipe</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  {odts.map((item: odtType, index) => (
                    <tr key={index}>
                      <th scope="row">{index + 1}</th>
                      <td>{item.nama_odt}</td>
                      <td>{item.tipe_odt}</td>
                      <td>{item.harga_odt}</td>
                      <td>
                        <Button
                          type="button"
                          className={["btn btn-success btn-sm me-2"]}
                        >
                          Detail
                        </Button>
                        <Button
                          type="link"
                          href={`odt/edit/${item.id}`}
                          className={["btn btn-warning btn-sm me-2"]}
                        >
                          Update
                        </Button>
                        <Button
                          type="link"
                          href={`odt/delete/${item.id}`}
                          className={["btn btn-danger btn-sm me-2"]}
                        >
                          Delete
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
